version: '3.8'
services:
  app:
    build: .
    container_name: my_app
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: npm run start:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network # 네트워크 추가
    environment:
      DB_HOST: db

  db:
    image: mysql:8
    container_name: my_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chatgps
    ports:
      - '3306:3306'
    networks:
      - my_network

networks: # 네트워크 정의
  my_network:
    driver: bridge

volumes:
  db_data:
